version: 2

sources:
  - name: supply_chain_source # ⬅️ ชื่อนามแฝงของ Source
    schema: public           # ⬅️ Schema ที่ตารางดิบอยู่
    tables:
      - name: stg_supply_chain # ⬅️ ชื่อตารางดิบ

models:
  # ⬇️ "name" นี้ต้องตรงกับ "ชื่อไฟล์.sql" ของคุณ (คือ supply_chain)
  - name: supply_chain
    description: "Cleaned, casted, and filtered core supply chain data. This is the single source of truth for downstream marts."
    # กำหนด Schema ที่โมเดลนี้จะถูกสร้าง (เผื่อ Config ข้างบนไม่ทำงาน)
    config:
      schema: core_core
      
    columns:
      - name: customer_id
        tests: [not_null]
      - name: order_item_id
        tests: [not_null]
      - name: sales
        tests:
          - not_null