version: 2

sources:
  - name: supply_chain_source # นี่คือชื่อ Source
    schema: public # นี่คือ Schema ที่ถูกต้อง
    tables:
      - name: stg_supply_chain # <--- แก้ชื่อตารางตรงนี้!

models:
  - name: stg_supply_chain
    description: Cleaned, typed staging view for supply chain
    columns:
      - name: customer_id
        tests: [not_null]
      - name: order_item_id
        tests: [not_null]
      - name: sales
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
